function [epoch, roll, roll_comp, yaw, yaw_comp] = importMSBDataATT(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [EPOCH, ROLL, ROLL_COMP, YAW, YAW_COMP] = IMPORTFILE(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as column vectors.
%
%  [EPOCH, ROLL, ROLL_COMP, YAW, YAW_COMP] = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [epoch, roll, roll_comp, yaw, yaw_comp] = importfile("D:\Uni_Bremen\01_Arbeit\Messboxen\Neigunsmessung\MSB-Messung\MSB0021-A-13-04-22\att_msb-0021-a_20220413T130000+0000.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Apr-2022 16:01:22

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["epoch", "roll", "roll_comp", "yaw", "yaw_comp"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
epoch = tbl.epoch;
roll = tbl.roll;
roll_comp = tbl.roll_comp;
yaw = tbl.yaw;
yaw_comp = tbl.yaw_comp;
end