function [epoch, acc_x, acc_y, acc_z, rot_x, rot_y, rot_z, mag_x, mag_y, mag_z, temp] = importMSBDataIMU(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [EPOCH, ACC_X, ACC_Y, ACC_Z, ROT_X, ROT_Y, ROT_Z, MAG_X, MAG_Y,
%  MAG_Z, TEMP] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [EPOCH, ACC_X, ACC_Y, ACC_Z, ROT_X, ROT_Y, ROT_Z, MAG_X, MAG_Y,
%  MAG_Z, TEMP] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [epoch, acc_x, acc_y, acc_z, rot_x, rot_y, rot_z, mag_x, mag_y, mag_z, temp] = importfile("D:\Uni_Bremen\01_Arbeit\Messboxen\Neigunsmessung\MSB-Messung\MSB0021-A-13-04-22\imu_msb-0021-a_20220413T130000+0000.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Apr-2022 16:02:29

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["epoch", "acc_x", "acc_y", "acc_z", "rot_x", "rot_y", "rot_z", "mag_x", "mag_y", "mag_z", "temp"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
epoch = tbl.epoch;
acc_x = tbl.acc_x;
acc_y = tbl.acc_y;
acc_z = tbl.acc_z;
rot_x = tbl.rot_x;
rot_y = tbl.rot_y;
rot_z = tbl.rot_z;
mag_x = tbl.mag_x;
mag_y = tbl.mag_y;
mag_z = tbl.mag_z;
temp = tbl.temp;
end